# Generated by Django 5.1.4 on 2024-12-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    def create_groups(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.get_or_create(name='Admin')
        Group.objects.get_or_create(name='Organizer')
        Group.objects.get_or_create(name='Attendee')

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
